platform :ios, '8.1'

pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtils'
pod 'Facebook-iOS-SDK'
pod 'Reachability'
pod 'ASIHTTPRequest'
pod 'SBJson', '~> 3'
pod 'HPGrowingTextView'
pod 'ODRefreshControl'
pod 'ActionSheetPicker-3.0'
pod 'JGActionSheet'
pod 'M13OrderedDictionary'
pod 'Stripe'
pod 'Stripe/ApplePay'
pod 'PaymentKit'
pod 'BKMoneyKit'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'BButton'
pod 'UICountingLabel'
pod 'ApplePayStubs'
pod 'Shimmer'
pod 'EAIntroView'
pod 'IQDropDownTextField'
